spring:
  datasource:
    #url: jdbc:h2:tcp://localhost/~/test;DB_CLOSE_DELAY=-1
    url: jdbc:h2:mem:test
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    #hikari:
      #jdbc-url: jdbc:postgresql://localhost:5432/postgres
      #username: postgres
      #password: 4991
      #driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop #지우고 다시 생성
    properties:
      hibernate:
#        show_sql: true #sysout을 통해 출력, 실제로는 안씀
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #log을 통해 출력
    org.hibernate.type: trace #sql 로그 중 어떤 파라매터가 들어가는지 보여줌
    